rootProject.name = "Monoceros"

include("plugin")
include("project:common")
include("project:common-impl")
include("project:module-bukkit")
include("project:module-command")
include("project:module-dispatcher")
include("project:module-script")
include("project:module-schedule")
include("project:module-volatility")
include("project:module-wireshark")
include("project:workflow-action")
include("project:workflow-property")
include("project:workflow-resources")
include("project:module-legacy-api")
include("project:module-modern")
include("project:module-java17")
include("project:module-java21")
include("project:extension-action-entity")
include("project:extension-action-event")
include("project:extension-action-illusion")
include("project:extension-action-item")
include("project:extension-action-memory")
include("project:extension-action-target")
include("project:extension-property-common")
include("project:extension-property-entity")
